//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funbit.Ets.Telemetry.Server {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringLib {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLib() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Funbit.Ets.Telemetry.Server.StringLib", typeof(StringLib).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Execute ETS2/ATS Telemetry Server.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddShortCut_Desciption {
            get {
                return ResourceManager.GetString("AddShortCut_Desciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shortcut was been installed successfully!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddShortCut_Done {
            get {
                return ResourceManager.GetString("AddShortCut_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telemetry Server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddShortCut_Name {
            get {
                return ResourceManager.GetString("AddShortCut_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Another ETS2/ATS Telemetry Server instance is already running!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AnotherInstanceRunning {
            get {
                return ResourceManager.GetString("AnotherInstanceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telemetry API URL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string apiEndpointUrlTitleLabel {
            get {
                return ResourceManager.GetString("apiEndpointUrlTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTML5 App URL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string appUrlTitleLabel {
            get {
                return ResourceManager.GetString("appUrlTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Checking {
            get {
                return ResourceManager.GetString("Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   -Bit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CurrentVersion_Bit {
            get {
                return ResourceManager.GetString("CurrentVersion_Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///    running application on.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CurrentVersion_Running {
            get {
                return ResourceManager.GetString("CurrentVersion_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UNSTALL MODE과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CurrentVersion_UninstallMode {
            get {
                return ResourceManager.GetString("CurrentVersion_UninstallMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Done과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_Install {
            get {
                return ResourceManager.GetString("Error_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_Network {
            get {
                return ResourceManager.GetString("Error_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_Process {
            get {
                return ResourceManager.GetString("Error_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setup error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_Setup {
            get {
                return ResourceManager.GetString("Error_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adding Firewall rule...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_AddRule {
            get {
                return ResourceManager.GetString("Firewall_AddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking Firewall rule...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_CheckRule {
            get {
                return ResourceManager.GetString("Firewall_CheckRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to add Firewall rule과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_FailedAddRule {
            get {
                return ResourceManager.GetString("Firewall_FailedAddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to check Firewall rule status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_FailedCheckRule {
            get {
                return ResourceManager.GetString("Firewall_FailedCheckRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to delete Firewall rule과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_FailedRmRule {
            get {
                return ResourceManager.GetString("Firewall_FailedRmRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting Firewall rule...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_RmRule {
            get {
                return ResourceManager.GetString("Firewall_RmRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ETS2 TELEMETRY SERVER (PORT 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_RuleName {
            get {
                return ResourceManager.GetString("Firewall_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot configure Windows Firewall.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_WFMissing1 {
            get {
                return ResourceManager.GetString("Firewall_WFMissing1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you are using some 3rd-party firewall please과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_WFMissing2 {
            get {
                return ResourceManager.GetString("Firewall_WFMissing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TCP port manually, open!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_WFMissing3 {
            get {
                return ResourceManager.GetString("Firewall_WFMissing3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TCP port manually, close!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_WFMissing3_1 {
            get {
                return ResourceManager.GetString("Firewall_WFMissing3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setup status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string groupBox {
            get {
                return ResourceManager.GetString("groupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string groupBox1 {
            get {
                return ResourceManager.GetString("groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string helpLabel {
            get {
                return ResourceManager.GetString("helpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server has been successfully installed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Install_Mode_Fin1 {
            get {
                return ResourceManager.GetString("Install_Mode_Fin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press OK to start the server.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Install_Mode_Fin2 {
            get {
                return ResourceManager.GetString("Install_Mode_Fin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server has been installed with errors.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Install_Mode_NotFin1 {
            get {
                return ResourceManager.GetString("Install_Mode_NotFin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press OK to start the server.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Install_Mode_NotFin2 {
            get {
                return ResourceManager.GetString("Install_Mode_NotFin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    port. Add friewall rule for과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Install_Status_firewall {
            get {
                return ResourceManager.GetString("Install_Status_firewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Install_Status_okButton {
            get {
                return ResourceManager.GetString("Install_Status_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install ETS2/ATS telemetry plugin DLL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Install_Status_plugin {
            get {
                return ResourceManager.GetString("Install_Status_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   . Add ACL rule for과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Install_Status_urlReservation {
            get {
                return ResourceManager.GetString("Install_Status_urlReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   In order to proceed the ETS2/ATS game must not be running.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsEts2Running1 {
            get {
                return ResourceManager.GetString("IsEts2Running1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please exit the game and try again.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsEts2Running2 {
            get {
                return ResourceManager.GetString("IsEts2Running2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Donate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Menu_Help_Donation {
            get {
                return ResourceManager.GetString("Menu_Help_Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Translate과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Menu_Help_Translate {
            get {
                return ResourceManager.GetString("Menu_Help_Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Menu_Server {
            get {
                return ResourceManager.GetString("Menu_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add Shortcut at Desktop과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Menu_Server_ShortCut {
            get {
                return ResourceManager.GetString("Menu_Server_ShortCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uninstall과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Menu_Server_Uninstall {
            get {
                return ResourceManager.GetString("Menu_Server_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Found following network interfaces과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NetworkHelper_GetAllNetInter {
            get {
                return ResourceManager.GetString("NetworkHelper_GetAllNetInter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System does not have any registered network interfaces that are connected to a network.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string NetworkHelper_Notfoundinter {
            get {
                return ResourceManager.GetString("NetworkHelper_Notfoundinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network Interfaces과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string networkInterfaceTitleLabel {
            get {
                return ResourceManager.GetString("networkInterfaceTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string okButton {
            get {
                return ResourceManager.GetString("okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;s plugin dll file backing up...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_BackupDLL {
            get {
                return ResourceManager.GetString("Plugin_BackupDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    - Select game path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_BrowserDes {
            get {
                return ResourceManager.GetString("Plugin_BrowserDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking plugin DLL files...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_CheckDLL {
            get {
                return ResourceManager.GetString("Plugin_CheckDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///    - Checking Path과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_CheckPath {
            get {
                return ResourceManager.GetString("Plugin_CheckPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///    - Copy Plugin DLL File과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_CopyDLL {
            get {
                return ResourceManager.GetString("Plugin_CopyDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fail과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_Failed {
            get {
                return ResourceManager.GetString("Plugin_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_Ok {
            get {
                return ResourceManager.GetString("Plugin_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;s game path, Could not detect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_PathVaild1 {
            get {
                return ResourceManager.GetString("Plugin_PathVaild1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you do not have 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_PathVaild2 {
            get {
                return ResourceManager.GetString("Plugin_PathVaild2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    installed press [Cancel] to skip,과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_PathVaild3 {
            get {
                return ResourceManager.GetString("Plugin_PathVaild3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   otherwise press [OK] to select path manually.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_PathVaild4 {
            get {
                return ResourceManager.GetString("Plugin_PathVaild4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   For example : 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_PathVaild5 {
            get {
                return ResourceManager.GetString("Plugin_PathVaild5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running command line과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcessHelper_RunArgs {
            get {
                return ResourceManager.GetString("ProcessHelper_RunArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to start process과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcessHelper_RunFailed {
            get {
                return ResourceManager.GetString("ProcessHelper_RunFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server IP과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string serverIpTitleLabel {
            get {
                return ResourceManager.GetString("serverIpTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StaticFileController_ISError {
            get {
                return ResourceManager.GetString("StaticFileController_ISError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Page not found!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string StaticFileController_NotFoud {
            get {
                return ResourceManager.GetString("StaticFileController_NotFoud", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Connected to과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string statusLabel_ConnectedAt {
            get {
                return ResourceManager.GetString("statusLabel_ConnectedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connected to the simulator과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string statusLabel_ConnectedSim {
            get {
                return ResourceManager.GetString("statusLabel_ConnectedSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simulator is not running과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string statusLabel_NotRunningSim {
            get {
                return ResourceManager.GetString("statusLabel_NotRunningSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Simulator is running과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string statusLabel_RunningSim {
            get {
                return ResourceManager.GetString("statusLabel_RunningSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string statusTitleLabel {
            get {
                return ResourceManager.GetString("statusTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ETS2/ATS Telemetry Server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setup과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Setup {
            get {
                return ResourceManager.GetString("Title_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Double-click to restore과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string trayIcon_DoubleClick {
            get {
                return ResourceManager.GetString("trayIcon_DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Already shown과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string trayIcon_Tag {
            get {
                return ResourceManager.GetString("trayIcon_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server has been successfully uninstalled.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uninstall_Mode_Fin1 {
            get {
                return ResourceManager.GetString("Uninstall_Mode_Fin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press OK to exit과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uninstall_Mode_Fin2 {
            get {
                return ResourceManager.GetString("Uninstall_Mode_Fin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server has been unstinalled with errors.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uninstall_Mode_NotFin1 {
            get {
                return ResourceManager.GetString("Uninstall_Mode_NotFin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press OK to exit.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uninstall_Mode_NotFin2 {
            get {
                return ResourceManager.GetString("Uninstall_Mode_NotFin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server is not installed, nothing to uninstall.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uninstall_NotInstall {
            get {
                return ResourceManager.GetString("Uninstall_NotInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///    port, Delete firewall rule for과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uninstall_Status_firewall {
            get {
                return ResourceManager.GetString("Uninstall_Status_firewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uninstall과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uninstall_Status_okButton {
            get {
                return ResourceManager.GetString("Uninstall_Status_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uninstall ETS2/ATS telemetry plugin DLL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uninstall_Status_plugin {
            get {
                return ResourceManager.GetString("Uninstall_Status_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   , Delete ACL rule for과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uninstall_Status_urlReservation {
            get {
                return ResourceManager.GetString("Uninstall_Status_urlReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Adding ACL rule...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UrlReservation_AddRule {
            get {
                return ResourceManager.GetString("UrlReservation_AddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Checking ACL rule status...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UrlReservation_CheckRule {
            get {
                return ResourceManager.GetString("UrlReservation_CheckRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to add URL ACL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UrlReservation_FailedAddRule {
            get {
                return ResourceManager.GetString("UrlReservation_FailedAddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to check URL ACL status과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UrlReservation_FailedCheckRule {
            get {
                return ResourceManager.GetString("UrlReservation_FailedCheckRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to delete URL ACL과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UrlReservation_FailedRmRule {
            get {
                return ResourceManager.GetString("UrlReservation_FailedRmRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Deleting ACL rule...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UrlReservation_RmRule {
            get {
                return ResourceManager.GetString("UrlReservation_RmRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warining과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
