//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Funbit.Ets.Telemetry.Server {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringLib {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLib() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Funbit.Ets.Telemetry.Server.StringLib", typeof(StringLib).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   ETS2/ATS Telemetry 서버를 실행 합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddShortCut_Desciption {
            get {
                return ResourceManager.GetString("AddShortCut_Desciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   바로가기가 바탕화면에 생성 되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddShortCut_Done {
            get {
                return ResourceManager.GetString("AddShortCut_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telemetry 서버과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string AddShortCut_Name {
            get {
                return ResourceManager.GetString("AddShortCut_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telemetry API 주소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string apiEndpointUrlTitleLabel {
            get {
                return ResourceManager.GetString("apiEndpointUrlTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HTML5 앱 주소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string appUrlTitleLabel {
            get {
                return ResourceManager.GetString("appUrlTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   비트과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CurrentVersion_Bit {
            get {
                return ResourceManager.GetString("CurrentVersion_Bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에서 실행중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CurrentVersion_Running {
            get {
                return ResourceManager.GetString("CurrentVersion_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   제거 모드과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CurrentVersion_UninstallMode {
            get {
                return ResourceManager.GetString("CurrentVersion_UninstallMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   완료과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설치 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_Install {
            get {
                return ResourceManager.GetString("Error_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   네트워크 오류과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_Network {
            get {
                return ResourceManager.GetString("Error_Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   프로세스 에러과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_Process {
            get {
                return ResourceManager.GetString("Error_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정 에러과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Error_Setup {
            get {
                return ResourceManager.GetString("Error_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   방화벽 규칙 추가중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_AddRule {
            get {
                return ResourceManager.GetString("Firewall_AddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   방화벽 규칙 확인중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_CheckRule {
            get {
                return ResourceManager.GetString("Firewall_CheckRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   방화벽 규칙 추가 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_FailedAddRule {
            get {
                return ResourceManager.GetString("Firewall_FailedAddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   방화벽 규칙 상태 확인 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_FailedCheckRule {
            get {
                return ResourceManager.GetString("Firewall_FailedCheckRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   방화벽 규칙 제거 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_FailedRmRule {
            get {
                return ResourceManager.GetString("Firewall_FailedRmRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   방화벽 규칙 제거중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_RmRule {
            get {
                return ResourceManager.GetString("Firewall_RmRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ETS2 TELEMETRY 서버 (포트 과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_RuleName {
            get {
                return ResourceManager.GetString("Firewall_RuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   윈도우 방화벽에 연결 할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_WFMissing1 {
            get {
                return ResourceManager.GetString("Firewall_WFMissing1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   만약 제3자 소프트웨어 백신(V3, 카스퍼스키 등)을 사용중 이라면,과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_WFMissing2 {
            get {
                return ResourceManager.GetString("Firewall_WFMissing2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   번 TCP 포트를 직접 열어주세요!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_WFMissing3 {
            get {
                return ResourceManager.GetString("Firewall_WFMissing3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   번 TCP 포트를 직접 닫아주세요!과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Firewall_WFMissing3_1 {
            get {
                return ResourceManager.GetString("Firewall_WFMissing3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정 상태과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string groupBox {
            get {
                return ResourceManager.GetString("groupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버 상태과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string groupBox1 {
            get {
                return ResourceManager.GetString("groupBox1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도움말과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string helpLabel {
            get {
                return ResourceManager.GetString("helpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   알림과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버가 성공적으로 설치되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Install_Mode_Fin1 {
            get {
                return ResourceManager.GetString("Install_Mode_Fin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인을 누르시면 서버가 시작됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Install_Mode_Fin2 {
            get {
                return ResourceManager.GetString("Install_Mode_Fin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버가 설치되었지만 오류가 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Install_Mode_NotFin1 {
            get {
                return ResourceManager.GetString("Install_Mode_NotFin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인을 누르시면 종료됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Install_Mode_NotFin2 {
            get {
                return ResourceManager.GetString("Install_Mode_NotFin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   번 포트에 대한 방화벽 허용 규칙을 추가합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Install_Status_firewall {
            get {
                return ResourceManager.GetString("Install_Status_firewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설치과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Install_Status_okButton {
            get {
                return ResourceManager.GetString("Install_Status_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ETS2/ATS telemetry 플로그인 DLL을 설치합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Install_Status_plugin {
            get {
                return ResourceManager.GetString("Install_Status_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에 대한 ACL 허용 규칙을 추가합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Install_Status_urlReservation {
            get {
                return ResourceManager.GetString("Install_Status_urlReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정 과정중엔 ETS2 혹은 ATS가 실행중이면 안됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsEts2Running1 {
            get {
                return ResourceManager.GetString("IsEts2Running1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   게임을 우선 종료하시고, 다시시도 해주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string IsEts2Running2 {
            get {
                return ResourceManager.GetString("IsEts2Running2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   도움말과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이 프로그램은...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Menu_Help_About {
            get {
                return ResourceManager.GetString("Menu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   원 제작자에게 기부과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Menu_Help_Donation {
            get {
                return ResourceManager.GetString("Menu_Help_Donation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   번역과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Menu_Help_Translate {
            get {
                return ResourceManager.GetString("Menu_Help_Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Menu_Server {
            get {
                return ResourceManager.GetString("Menu_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   바탕화면에 바로가기 추가과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Menu_Server_ShortCut {
            get {
                return ResourceManager.GetString("Menu_Server_ShortCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설치 제거과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Menu_Server_Uninstall {
            get {
                return ResourceManager.GetString("Menu_Server_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   네트워크 인터페이스과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string networkInterfaceTitleLabel {
            get {
                return ResourceManager.GetString("networkInterfaceTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설치과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string okButton {
            get {
                return ResourceManager.GetString("okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   의 플러그인 DLL 파일을 백업중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_BackupDLL {
            get {
                return ResourceManager.GetString("Plugin_BackupDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   의 경로를 선택 해 주세요.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_BrowserDes {
            get {
                return ResourceManager.GetString("Plugin_BrowserDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   플러그인 DLL 파일 확인중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_CheckDLL {
            get {
                return ResourceManager.GetString("Plugin_CheckDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경로 확인중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_CheckPath {
            get {
                return ResourceManager.GetString("Plugin_CheckPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   플러그인 DLL 파일을 복사중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_CopyDLL {
            get {
                return ResourceManager.GetString("Plugin_CopyDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_Failed {
            get {
                return ResourceManager.GetString("Plugin_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_Ok {
            get {
                return ResourceManager.GetString("Plugin_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   의 경로를 탐색하지 못했습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_PathVaild1 {
            get {
                return ResourceManager.GetString("Plugin_PathVaild1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   만약과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_PathVaild2 {
            get {
                return ResourceManager.GetString("Plugin_PathVaild2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   를 설치하지 않았다면 [취소]를 눌러 넘깁니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_PathVaild3 {
            get {
                return ResourceManager.GetString("Plugin_PathVaild3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   아니라면 [확인]을 눌러 경로를 직접 설정합니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_PathVaild4 {
            get {
                return ResourceManager.GetString("Plugin_PathVaild4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   예시과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Plugin_PathVaild5 {
            get {
                return ResourceManager.GetString("Plugin_PathVaild5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실행 명령어과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcessHelper_RunArgs {
            get {
                return ResourceManager.GetString("ProcessHelper_RunArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   실행 실패한 프로세스과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ProcessHelper_RunFailed {
            get {
                return ResourceManager.GetString("ProcessHelper_RunFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버 주소과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string serverIpTitleLabel {
            get {
                return ResourceManager.GetString("serverIpTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에 연결됨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string statusLabel_ConnectedAt {
            get {
                return ResourceManager.GetString("statusLabel_ConnectedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시뮬레이터에 연결됨과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string statusLabel_ConnectedSim {
            get {
                return ResourceManager.GetString("statusLabel_ConnectedSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시뮬레이터가 실행중이 아님과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string statusLabel_NotRunningSim {
            get {
                return ResourceManager.GetString("statusLabel_NotRunningSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시뮬레이터가 실행중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string statusLabel_RunningSim {
            get {
                return ResourceManager.GetString("statusLabel_RunningSim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   상태과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string statusTitleLabel {
            get {
                return ResourceManager.GetString("statusTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ETS2/ATS Telemetry 서버과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설정과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Title_Setup {
            get {
                return ResourceManager.GetString("Title_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   더블클릭하여 열기과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string trayIcon_DoubleClick {
            get {
                return ResourceManager.GetString("trayIcon_DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 열려 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string trayIcon_Tag {
            get {
                return ResourceManager.GetString("trayIcon_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버가 성공적으로 제거되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uninstall_Mode_Fin1 {
            get {
                return ResourceManager.GetString("Uninstall_Mode_Fin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인을 누르면 종료됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uninstall_Mode_Fin2 {
            get {
                return ResourceManager.GetString("Uninstall_Mode_Fin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버가 제거되었지만 오류가 있습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uninstall_Mode_NotFin1 {
            get {
                return ResourceManager.GetString("Uninstall_Mode_NotFin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   확인을 누르시면 종료됩니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uninstall_Mode_NotFin2 {
            get {
                return ResourceManager.GetString("Uninstall_Mode_NotFin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   서버가 설치되어 있지 않습니다. 제거 할 수 없습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uninstall_NotInstall {
            get {
                return ResourceManager.GetString("Uninstall_NotInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   번 포트에 대한 방화벽 허용 규칙을 지웁니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uninstall_Status_firewall {
            get {
                return ResourceManager.GetString("Uninstall_Status_firewall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   설치 제거과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uninstall_Status_okButton {
            get {
                return ResourceManager.GetString("Uninstall_Status_okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ETS2/ATS Telemetry 플러그인 DLL을 지웁니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uninstall_Status_plugin {
            get {
                return ResourceManager.GetString("Uninstall_Status_plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   에 대한 ACL 규칙을 지웁니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Uninstall_Status_urlReservation {
            get {
                return ResourceManager.GetString("Uninstall_Status_urlReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACL 규칙을 추가중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UrlReservation_AddRule {
            get {
                return ResourceManager.GetString("UrlReservation_AddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACL 규칙 확인중과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UrlReservation_CheckRule {
            get {
                return ResourceManager.GetString("UrlReservation_CheckRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL ACL 규칙 추가 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UrlReservation_FailedAddRule {
            get {
                return ResourceManager.GetString("UrlReservation_FailedAddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL ACL 규칙 상태 확인 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UrlReservation_FailedCheckRule {
            get {
                return ResourceManager.GetString("UrlReservation_FailedCheckRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   URL ACL 규칙 제거 실패과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UrlReservation_FailedRmRule {
            get {
                return ResourceManager.GetString("UrlReservation_FailedRmRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ACL 규칙 제거중...과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string UrlReservation_RmRule {
            get {
                return ResourceManager.GetString("UrlReservation_RmRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   경고과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
